INCORRECT DB NAME

(flaskp27) c:\x_repo\mundus\dojo\python\sql_flask\first_sql>py server.py
Traceback (most recent call last):
  File "server.py", line 4, in <module>
    mysql = MySQLConnector(app,'mydb')
  File "c:\x_repo\mundus\dojo\python\sql_flask\first_sql\mysqlconnection.py", line 39, in MySQLConnector
    return MySQLConnection(app, db)
  File "c:\x_repo\mundus\dojo\python\sql_flask\first_sql\mysqlconnection.py", line 9, in __init__
    'database': dddddb,
NameError: global name 'dddddb' is not defined

INCORRECT USER NAME
super(Connection, self).__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'rrrrroot'@'localhost' (using password: YES)")

INCORRECT PASSWORD
super(Connection, self).__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

INCORRECT PORT ASSIGNMENT
super(Connection, self).__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' (10061)")
